"""initial core platform schema

Creates the core platform tables (users, RBAC, organizations, workspaces,
campaigns, templates, media, communication, notifications, audit, integrations,
AI, system, security, misc, auth extras, legacy automation, legacy reports).

Module-specific tables are owned by later migrations:

* 0002_volunteers    - volunteer module
* 0003_disasters     - disaster module
* 0004_public_access - public information / QR module
* 0005_translation   - multilingual entity translations
* 0006_analytics     - analytics platform tables
* 0007_workflow      - workflow engine tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-07
"""
from __future__ import annotations

from alembic import op


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE TABLE feature_flags (\n\tkey VARCHAR(120) NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tdescription VARCHAR(500) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\trollout_percent INTEGER NOT NULL, \n\tscope VARCHAR(30) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE UNIQUE INDEX ix_feature_flags_key ON feature_flags (key)')
    op.execute('CREATE TABLE health_checks (\n\tcomponent VARCHAR(60) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tlatency_ms NUMERIC(10, 2) NOT NULL, \n\tdetail VARCHAR(500) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE INDEX ix_health_checks_component ON health_checks (component)')
    op.execute('CREATE TABLE help_articles (\n\ttitle VARCHAR(200) NOT NULL, \n\tslug VARCHAR(200) NOT NULL, \n\tcategory VARCHAR(60) NOT NULL, \n\tbody TEXT NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tUNIQUE (slug)\n)')
    op.execute('CREATE TABLE knowledge_articles (\n\ttitle VARCHAR(200) NOT NULL, \n\tbody TEXT NOT NULL, \n\ttags JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE TABLE licenses (\n\tplan VARCHAR(60) NOT NULL, \n\tseats INTEGER NOT NULL, \n\tseats_used INTEGER NOT NULL, \n\trenews_on TIMESTAMP WITH TIME ZONE, \n\tcontract_id VARCHAR(80) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE TABLE monitoring_metrics (\n\tname VARCHAR(120) NOT NULL, \n\tvalue NUMERIC(14, 4) NOT NULL, \n\tunit VARCHAR(30) NOT NULL, \n\tat TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE INDEX ix_monitoring_metrics_name ON monitoring_metrics (name)')
    op.execute('CREATE TABLE organizations (\n\tname VARCHAR(200) NOT NULL, \n\tslug VARCHAR(120) NOT NULL, \n\ttype VARCHAR(60) NOT NULL, \n\tstatus VARCHAR(40) NOT NULL, \n\twebsite VARCHAR(255), \n\tcontact_email VARCHAR(255), \n\tmember_count INTEGER NOT NULL, \n\tregion VARCHAR(120), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tUNIQUE (slug)\n)')
    op.execute('CREATE INDEX ix_organizations_name ON organizations (name)')
    op.execute('CREATE TABLE roles (\n\tname VARCHAR(64) NOT NULL, \n\tdescription VARCHAR(255), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE UNIQUE INDEX ix_roles_name ON roles (name)')
    op.execute('CREATE TABLE system_configurations (\n\tsection VARCHAR(60) NOT NULL, \n\tkey VARCHAR(120) NOT NULL, \n\tvalue JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE INDEX ix_system_configurations_section ON system_configurations (section)')
    op.execute('CREATE TABLE users (\n\temail VARCHAR(255) NOT NULL, \n\tfull_name VARCHAR(160) NOT NULL, \n\thashed_password VARCHAR(255) NOT NULL, \n\tavatar_url VARCHAR(500), \n\tis_active BOOLEAN NOT NULL, \n\temail_verified_at TIMESTAMP WITH TIME ZONE, \n\tdefault_workspace_id UUID, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id)\n)')
    op.execute('CREATE UNIQUE INDEX ix_users_email ON users (email)')
    op.execute('CREATE TABLE account_lockouts (\n\tuser_id UUID NOT NULL, \n\tlocked_until TIMESTAMP WITH TIME ZONE, \n\tfailed_attempts INTEGER NOT NULL, \n\treason VARCHAR(120), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE UNIQUE INDEX ix_account_lockouts_user_id ON account_lockouts (user_id)')
    op.execute('CREATE TABLE favorites (\n\tuser_id UUID NOT NULL, \n\ttarget_type VARCHAR(60) NOT NULL, \n\ttarget_id VARCHAR(64) NOT NULL, \n\tPRIMARY KEY (user_id, target_type, target_id), \n\tCONSTRAINT uq_favorite UNIQUE (user_id, target_type, target_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE TABLE login_attempts (\n\temail VARCHAR(255) NOT NULL, \n\tuser_id UUID, \n\tip_address VARCHAR(64), \n\tuser_agent VARCHAR(255), \n\tsuccess BOOLEAN NOT NULL, \n\treason VARCHAR(120), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL\n)')
    op.execute('CREATE INDEX ix_login_attempts_email ON login_attempts (email)')
    op.execute('CREATE INDEX ix_login_attempts_success ON login_attempts (success)')
    op.execute('CREATE TABLE mfa_factors (\n\tuser_id UUID NOT NULL, \n\tfactor_type VARCHAR(20) NOT NULL, \n\tlabel VARCHAR(120) NOT NULL, \n\tsecret VARCHAR(255), \n\tverified BOOLEAN NOT NULL, \n\tlast_used_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_mfa_factors_user_id ON mfa_factors (user_id)')
    op.execute('CREATE TABLE mfa_recovery_codes (\n\tuser_id UUID NOT NULL, \n\tcode_hash VARCHAR(255) NOT NULL, \n\tused_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_mfa_recovery_codes_user_id ON mfa_recovery_codes (user_id)')
    op.execute('CREATE TABLE notification_preferences (\n\tuser_id UUID NOT NULL, \n\tchannel VARCHAR(30) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tquiet_hours JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_notification_preferences_user_id ON notification_preferences (user_id)')
    op.execute('CREATE TABLE notifications (\n\tuser_id UUID NOT NULL, \n\ttitle VARCHAR(200) NOT NULL, \n\tmessage TEXT NOT NULL, \n\tcategory VARCHAR(30) NOT NULL, \n\tpriority VARCHAR(20) NOT NULL, \n\tread BOOLEAN NOT NULL, \n\tarchived BOOLEAN NOT NULL, \n\thref VARCHAR(500), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_notifications_user_id ON notifications (user_id)')
    op.execute('CREATE TABLE password_history (\n\tuser_id UUID NOT NULL, \n\thashed_password VARCHAR(255) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_password_history_user_id ON password_history (user_id)')
    op.execute('CREATE TABLE sessions (\n\tuser_id UUID NOT NULL, \n\trefresh_token_hash VARCHAR(255) NOT NULL, \n\tip_address VARCHAR(64), \n\tuser_agent VARCHAR(255), \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_sessions_user_id ON sessions (user_id)')
    op.execute('CREATE TABLE trusted_devices (\n\tuser_id UUID NOT NULL, \n\tdevice_id VARCHAR(128) NOT NULL, \n\tlabel VARCHAR(160) NOT NULL, \n\tdevice_type VARCHAR(32) NOT NULL, \n\tbrowser VARCHAR(64), \n\toperating_system VARCHAR(64), \n\ttrusted BOOLEAN NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_trusted_devices_device_id ON trusted_devices (device_id)')
    op.execute('CREATE INDEX ix_trusted_devices_trusted ON trusted_devices (trusted)')
    op.execute('CREATE INDEX ix_trusted_devices_user_id ON trusted_devices (user_id)')
    op.execute('CREATE TABLE user_preferences (\n\tuser_id UUID NOT NULL, \n\tkey VARCHAR(120) NOT NULL, \n\tvalue JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_user_preferences_user_id ON user_preferences (user_id)')
    op.execute('CREATE TABLE user_roles (\n\tuser_id UUID NOT NULL, \n\trole_id UUID NOT NULL, \n\tPRIMARY KEY (user_id, role_id), \n\tCONSTRAINT uq_user_role UNIQUE (user_id, role_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, \n\tFOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE\n)')
    op.execute('CREATE TABLE verification_tokens (\n\tuser_id UUID NOT NULL, \n\tpurpose VARCHAR(32) NOT NULL, \n\ttoken_hash VARCHAR(255) NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tconsumed_at TIMESTAMP WITH TIME ZONE, \n\tip_address VARCHAR(64), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_verification_tokens_user_id ON verification_tokens (user_id)')
    op.execute('CREATE INDEX ix_verification_tokens_purpose ON verification_tokens (purpose)')
    op.execute('CREATE UNIQUE INDEX ix_verification_tokens_token_hash ON verification_tokens (token_hash)')
    op.execute('CREATE TABLE workspaces (\n\torganization_id UUID NOT NULL, \n\tname VARCHAR(160) NOT NULL, \n\tslug VARCHAR(120) NOT NULL, \n\tplan VARCHAR(40) NOT NULL, \n\tregion VARCHAR(60) NOT NULL, \n\ttimezone VARCHAR(60) NOT NULL, \n\tprimary_language VARCHAR(10) NOT NULL, \n\tstorage_quota_gb INTEGER NOT NULL, \n\tapi_quota_monthly INTEGER NOT NULL, \n\tmember_count INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tUNIQUE (slug)\n)')
    op.execute('CREATE INDEX ix_workspaces_organization_id ON workspaces (organization_id)')
    op.execute('CREATE TABLE activity_logs (\n\tworkspace_id UUID, \n\tactor_id UUID, \n\tevent VARCHAR(80) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)')
    op.execute('CREATE INDEX ix_activity_logs_workspace_id ON activity_logs (workspace_id)')
    op.execute('CREATE INDEX ix_activity_logs_event ON activity_logs (event)')
    op.execute('CREATE TABLE ai_history (\n\tworkspace_id UUID NOT NULL, \n\tuser_id UUID, \n\tprompt TEXT NOT NULL, \n\tmodel VARCHAR(80) NOT NULL, \n\ttokens INTEGER NOT NULL, \n\tcontent TEXT NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)')
    op.execute('CREATE INDEX ix_ai_history_workspace_id ON ai_history (workspace_id)')
    op.execute('CREATE INDEX ix_ai_history_user_id ON ai_history (user_id)')
    op.execute('CREATE TABLE ai_prompts (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tcategory VARCHAR(60) NOT NULL, \n\tbody TEXT NOT NULL, \n\tvariables JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_ai_prompts_workspace_id ON ai_prompts (workspace_id)')
    op.execute('CREATE TABLE api_keys (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(120) NOT NULL, \n\tprefix VARCHAR(20) NOT NULL, \n\tkey_hash VARCHAR(255) NOT NULL, \n\trevoked BOOLEAN NOT NULL, \n\tlast_used_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_api_keys_workspace_id ON api_keys (workspace_id)')
    op.execute('CREATE TABLE audience (\n\tworkspace_id UUID NOT NULL, \n\tfull_name VARCHAR(160) NOT NULL, \n\temail VARCHAR(255), \n\tphone VARCHAR(40), \n\tlanguage VARCHAR(10) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\ttags VARCHAR[] NOT NULL, \n\tdistrict VARCHAR(120), \n\tstate VARCHAR(120), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_audience_email ON audience (email)')
    op.execute('CREATE INDEX ix_audience_workspace_id ON audience (workspace_id)')
    op.execute('CREATE TABLE audience_groups (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(160) NOT NULL, \n\tdescription VARCHAR(500), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_audience_groups_workspace_id ON audience_groups (workspace_id)')
    op.execute('CREATE TABLE audience_tags (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(80) NOT NULL, \n\tcolor VARCHAR(20) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_audience_tags_name ON audience_tags (name)')
    op.execute('CREATE INDEX ix_audience_tags_workspace_id ON audience_tags (workspace_id)')
    op.execute('CREATE TABLE audit_logs (\n\tworkspace_id UUID, \n\tactor_id UUID, \n\taction VARCHAR(50) NOT NULL, \n\tmodule VARCHAR(50) NOT NULL, \n\tentity_id VARCHAR(64), \n\tentity_label VARCHAR(200), \n\tip_address VARCHAR(64), \n\tuser_agent VARCHAR(255), \n\tmetadata JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)')
    op.execute('CREATE INDEX ix_audit_logs_module ON audit_logs (module)')
    op.execute('CREATE INDEX ix_audit_logs_actor_id ON audit_logs (actor_id)')
    op.execute('CREATE INDEX ix_audit_logs_action ON audit_logs (action)')
    op.execute('CREATE INDEX ix_audit_logs_workspace_id ON audit_logs (workspace_id)')
    op.execute('CREATE TABLE background_jobs (\n\tworkspace_id UUID, \n\tkind VARCHAR(60) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tprogress INTEGER NOT NULL, \n\tpayload JSONB NOT NULL, \n\tresult JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id)\n)')
    op.execute('CREATE INDEX ix_background_jobs_kind ON background_jobs (kind)')
    op.execute('CREATE INDEX ix_background_jobs_status ON background_jobs (status)')
    op.execute('CREATE INDEX ix_background_jobs_workspace_id ON background_jobs (workspace_id)')
    op.execute('CREATE TABLE campaigns (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tchannels VARCHAR[] NOT NULL, \n\taudience_count INTEGER NOT NULL, \n\tstarts_at TIMESTAMP WITH TIME ZONE, \n\tends_at TIMESTAMP WITH TIME ZONE, \n\towner_id UUID, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE, \n\tFOREIGN KEY(owner_id) REFERENCES users (id)\n)')
    op.execute('CREATE INDEX ix_campaigns_status ON campaigns (status)')
    op.execute('CREATE INDEX ix_campaigns_workspace_id ON campaigns (workspace_id)')
    op.execute('CREATE TABLE communication_channels (\n\tworkspace_id UUID NOT NULL, \n\tkind VARCHAR(30) NOT NULL, \n\tname VARCHAR(120) NOT NULL, \n\tprovider VARCHAR(80) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tconfig JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_communication_channels_workspace_id ON communication_channels (workspace_id)')
    op.execute('CREATE TABLE integrations (\n\tworkspace_id UUID NOT NULL, \n\tprovider VARCHAR(80) NOT NULL, \n\tkind VARCHAR(30) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tsettings JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_integrations_workspace_id ON integrations (workspace_id)')
    op.execute('CREATE TABLE legacy_workflow_definitions (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tdefinition JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_legacy_workflow_definitions_workspace_id ON legacy_workflow_definitions (workspace_id)')
    op.execute('CREATE TABLE media (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\tmime_type VARCHAR(120) NOT NULL, \n\tsize_bytes BIGINT NOT NULL, \n\turl VARCHAR(1024) NOT NULL, \n\tchecksum VARCHAR(128), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_media_workspace_id ON media (workspace_id)')
    op.execute('CREATE TABLE reports (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tkind VARCHAR(30) NOT NULL, \n\tscheduled BOOLEAN NOT NULL, \n\tlast_run_at TIMESTAMP WITH TIME ZONE, \n\tfilters JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_reports_workspace_id ON reports (workspace_id)')
    op.execute('CREATE TABLE retry_policies (\n\tworkspace_id UUID NOT NULL, \n\tchannel VARCHAR(30) NOT NULL, \n\tmax_attempts INTEGER NOT NULL, \n\tbackoff_seconds INTEGER NOT NULL, \n\tstrategy VARCHAR(30) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_retry_policies_workspace_id ON retry_policies (workspace_id)')
    op.execute('CREATE TABLE security_events (\n\tworkspace_id UUID, \n\tactor VARCHAR(120) NOT NULL, \n\tseverity VARCHAR(20) NOT NULL, \n\tevent VARCHAR(120) NOT NULL, \n\tip VARCHAR(64) NOT NULL, \n\tdetail VARCHAR(500) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id)\n)')
    op.execute('CREATE INDEX ix_security_events_event ON security_events (event)')
    op.execute('CREATE INDEX ix_security_events_workspace_id ON security_events (workspace_id)')
    op.execute('CREATE TABLE templates (\n\tworkspace_id UUID NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tcategory VARCHAR(60) NOT NULL, \n\tchannels VARCHAR[] NOT NULL, \n\tlanguage VARCHAR(10) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tbody TEXT NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_templates_workspace_id ON templates (workspace_id)')
    op.execute('CREATE TABLE translations (\n\tworkspace_id UUID NOT NULL, \n\tsource_language VARCHAR(10) NOT NULL, \n\ttarget_language VARCHAR(10) NOT NULL, \n\tsource_text TEXT NOT NULL, \n\ttranslated_text TEXT NOT NULL, \n\tquality NUMERIC(4, 3) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_translations_workspace_id ON translations (workspace_id)')
    op.execute('CREATE TABLE webhooks (\n\tworkspace_id UUID NOT NULL, \n\turl VARCHAR(1024) NOT NULL, \n\tevents JSONB NOT NULL, \n\tsecret VARCHAR(255) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tretry_count INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_webhooks_workspace_id ON webhooks (workspace_id)')
    op.execute('CREATE TABLE workspace_members (\n\tworkspace_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\trole VARCHAR(64) NOT NULL, \n\tPRIMARY KEY (workspace_id, user_id), \n\tCONSTRAINT uq_workspace_member UNIQUE (workspace_id, user_id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE, \n\tFOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)')
    op.execute('CREATE TABLE approvals (\n\tcampaign_id UUID NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\treviewer_id UUID, \n\tnote VARCHAR(1000), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE, \n\tFOREIGN KEY(reviewer_id) REFERENCES users (id)\n)')
    op.execute('CREATE INDEX ix_approvals_campaign_id ON approvals (campaign_id)')
    op.execute('CREATE TABLE campaign_audience (\n\tcampaign_id UUID NOT NULL, \n\taudience_id UUID NOT NULL, \n\tPRIMARY KEY (campaign_id, audience_id), \n\tFOREIGN KEY(campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE, \n\tFOREIGN KEY(audience_id) REFERENCES audience (id) ON DELETE CASCADE\n)')
    op.execute('CREATE TABLE campaign_templates (\n\tcampaign_id UUID NOT NULL, \n\ttemplate_id UUID NOT NULL, \n\tchannel VARCHAR(30) NOT NULL, \n\tPRIMARY KEY (campaign_id, template_id, channel), \n\tFOREIGN KEY(campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE, \n\tFOREIGN KEY(template_id) REFERENCES templates (id) ON DELETE CASCADE\n)')
    op.execute('CREATE TABLE deliveries (\n\tcampaign_id UUID NOT NULL, \n\tchannel VARCHAR(30) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tscheduled_at TIMESTAMP WITH TIME ZONE, \n\tattempts INTEGER NOT NULL, \n\tpriority INTEGER NOT NULL, \n\terror_code VARCHAR(80), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_deliveries_channel ON deliveries (channel)')
    op.execute('CREATE INDEX ix_deliveries_status ON deliveries (status)')
    op.execute('CREATE INDEX ix_deliveries_campaign_id ON deliveries (campaign_id)')
    op.execute('CREATE TABLE legacy_workflow_executions (\n\tworkflow_id UUID NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tcontext JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workflow_id) REFERENCES legacy_workflow_definitions (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_legacy_workflow_executions_workflow_id ON legacy_workflow_executions (workflow_id)')
    op.execute('CREATE TABLE template_versions (\n\ttemplate_id UUID NOT NULL, \n\tversion INTEGER NOT NULL, \n\tbody TEXT NOT NULL, \n\tnote VARCHAR(500), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(template_id) REFERENCES templates (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_template_versions_template_id ON template_versions (template_id)')
    op.execute('CREATE TABLE translation_history (\n\tworkspace_id UUID NOT NULL, \n\ttranslation_id UUID, \n\tstatus VARCHAR(30) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE, \n\tFOREIGN KEY(translation_id) REFERENCES translations (id)\n)')
    op.execute('CREATE INDEX ix_translation_history_workspace_id ON translation_history (workspace_id)')
    op.execute('CREATE TABLE delivery_recipients (\n\tdelivery_id UUID NOT NULL, \n\taudience_id UUID NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tdelivered_at TIMESTAMP WITH TIME ZONE, \n\terror_message TEXT, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(64), \n\tupdated_by VARCHAR(64), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(delivery_id) REFERENCES deliveries (id) ON DELETE CASCADE, \n\tFOREIGN KEY(audience_id) REFERENCES audience (id) ON DELETE CASCADE\n)')
    op.execute('CREATE INDEX ix_delivery_recipients_status ON delivery_recipients (status)')
    op.execute('CREATE INDEX ix_delivery_recipients_delivery_id ON delivery_recipients (delivery_id)')


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS delivery_recipients CASCADE")
    op.execute("DROP TABLE IF EXISTS translation_history CASCADE")
    op.execute("DROP TABLE IF EXISTS template_versions CASCADE")
    op.execute("DROP TABLE IF EXISTS legacy_workflow_executions CASCADE")
    op.execute("DROP TABLE IF EXISTS deliveries CASCADE")
    op.execute("DROP TABLE IF EXISTS campaign_templates CASCADE")
    op.execute("DROP TABLE IF EXISTS campaign_audience CASCADE")
    op.execute("DROP TABLE IF EXISTS approvals CASCADE")
    op.execute("DROP TABLE IF EXISTS workspace_members CASCADE")
    op.execute("DROP TABLE IF EXISTS webhooks CASCADE")
    op.execute("DROP TABLE IF EXISTS translations CASCADE")
    op.execute("DROP TABLE IF EXISTS templates CASCADE")
    op.execute("DROP TABLE IF EXISTS security_events CASCADE")
    op.execute("DROP TABLE IF EXISTS retry_policies CASCADE")
    op.execute("DROP TABLE IF EXISTS reports CASCADE")
    op.execute("DROP TABLE IF EXISTS media CASCADE")
    op.execute("DROP TABLE IF EXISTS legacy_workflow_definitions CASCADE")
    op.execute("DROP TABLE IF EXISTS integrations CASCADE")
    op.execute("DROP TABLE IF EXISTS communication_channels CASCADE")
    op.execute("DROP TABLE IF EXISTS campaigns CASCADE")
    op.execute("DROP TABLE IF EXISTS background_jobs CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_logs CASCADE")
    op.execute("DROP TABLE IF EXISTS audience_tags CASCADE")
    op.execute("DROP TABLE IF EXISTS audience_groups CASCADE")
    op.execute("DROP TABLE IF EXISTS audience CASCADE")
    op.execute("DROP TABLE IF EXISTS api_keys CASCADE")
    op.execute("DROP TABLE IF EXISTS ai_prompts CASCADE")
    op.execute("DROP TABLE IF EXISTS ai_history CASCADE")
    op.execute("DROP TABLE IF EXISTS activity_logs CASCADE")
    op.execute("DROP TABLE IF EXISTS workspaces CASCADE")
    op.execute("DROP TABLE IF EXISTS verification_tokens CASCADE")
    op.execute("DROP TABLE IF EXISTS user_roles CASCADE")
    op.execute("DROP TABLE IF EXISTS user_preferences CASCADE")
    op.execute("DROP TABLE IF EXISTS trusted_devices CASCADE")
    op.execute("DROP TABLE IF EXISTS sessions CASCADE")
    op.execute("DROP TABLE IF EXISTS password_history CASCADE")
    op.execute("DROP TABLE IF EXISTS notifications CASCADE")
    op.execute("DROP TABLE IF EXISTS notification_preferences CASCADE")
    op.execute("DROP TABLE IF EXISTS mfa_recovery_codes CASCADE")
    op.execute("DROP TABLE IF EXISTS mfa_factors CASCADE")
    op.execute("DROP TABLE IF EXISTS login_attempts CASCADE")
    op.execute("DROP TABLE IF EXISTS favorites CASCADE")
    op.execute("DROP TABLE IF EXISTS account_lockouts CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TABLE IF EXISTS system_configurations CASCADE")
    op.execute("DROP TABLE IF EXISTS roles CASCADE")
    op.execute("DROP TABLE IF EXISTS organizations CASCADE")
    op.execute("DROP TABLE IF EXISTS monitoring_metrics CASCADE")
    op.execute("DROP TABLE IF EXISTS licenses CASCADE")
    op.execute("DROP TABLE IF EXISTS knowledge_articles CASCADE")
    op.execute("DROP TABLE IF EXISTS help_articles CASCADE")
    op.execute("DROP TABLE IF EXISTS health_checks CASCADE")
    op.execute("DROP TABLE IF EXISTS feature_flags CASCADE")
